const axios = require('axios');
const { parseFiles } = require('./codeParser');
const { fixRailwayCompatibility } = require('./codeFixup');

const GITHUB_API = 'https://api.github.com';

function githubHeaders(token) {
  return {
    Authorization: `token ${token}`,
    'Content-Type': 'application/json',
    'User-Agent': 'Three-AI-Relay-Platform',
    Accept: 'application/vnd.github+json',
  };
}

async function createRepository(token, repoName, description, isPrivate = false) {
  try {
    const res = await axios.post(
      `${GITHUB_API}/user/repos`,
      { name: repoName, description, private: isPrivate, auto_init: true },
      { headers: githubHeaders(token) }
    );
    return res.data;
  } catch (err) {
    // 422 = repo already exists — fetch it instead
    if (err.response && err.response.status === 422) {
      const userRes = await axios.get(`${GITHUB_API}/user`, { headers: githubHeaders(token) });
      const owner = userRes.data.login;
      const repoRes = await axios.get(`${GITHUB_API}/repos/${owner}/${repoName}`, { headers: githubHeaders(token) });
      return repoRes.data;
    }
    throw err;
  }
}

async function getFileSha(token, owner, repo, filePath) {
  try {
    const res = await axios.get(
      `${GITHUB_API}/repos/${owner}/${repo}/contents/${filePath}`,
      { headers: githubHeaders(token) }
    );
    return res.data.sha;
  } catch {
    return null;
  }
}

async function putFile(token, owner, repo, filePath, content, message) {
  const sha = await getFileSha(token, owner, repo, filePath);
  const body = {
    message,
    content: Buffer.from(content).toString('base64'),
  };
  if (sha) body.sha = sha;
  await axios.put(
    `${GITHUB_API}/repos/${owner}/${repo}/contents/${filePath}`,
    body,
    { headers: githubHeaders(token) }
  );
}

async function enablePages(token, owner, repo) {
  try {
    await axios.post(
      `${GITHUB_API}/repos/${owner}/${repo}/pages`,
      { source: { branch: 'main', path: '/' } },
      { headers: githubHeaders(token) }
    );
  } catch (err) {
    if (err.response && (err.response.status === 409 || err.response.status === 422)) return;
    throw err;
  }
}

// Map artifact message_type to a readable filename
function artifactFilename(messageType) {
  const map = {
    chatgpt_design:     'design_spec.md',
    claude_build:       'build_code.txt',
    gemini_integration: 'integration_guide.md',
  };
  return map[messageType] || `${messageType}.txt`;
}

async function deployToGitHub(crossRefId, artifacts, prompt) {
  const token = process.env.GITHUB_TOKEN;
  if (!token) throw new Error('GITHUB_TOKEN environment variable is not set');

  const repoName = `relay-${crossRefId}`;
  const description = prompt ? prompt.slice(0, 120) : 'Built by Three-AI Relay Platform';

  const repo = await createRepository(token, repoName, description, false);
  const owner = repo.owner.login;

  // Separate artifact types
  const designArtifact = artifacts.find(a => (a.message_type || a.name || '').includes('design'));
  const buildArtifact  = artifacts.find(a => (a.message_type || a.name || '').includes('build'));
  const finalArtifact  = artifacts.find(a => (a.message_type || a.name || '').includes('final') || (a.message_type || a.name || '').includes('gemini'));

  // Parse Claude's build output into individual files then fix for Railway
  const rawParsed = buildArtifact && buildArtifact.content
    ? parseFiles(buildArtifact.content)
    : [];
  const parsedFiles = rawParsed.length > 0 ? fixRailwayCompatibility(rawParsed) : [];

  // Build the file manifest for the README
  const fileList = parsedFiles.map(f => `| \`${f.path}\` | Claude (build) |`).join('\n');

  const readme = `# ${repoName}

> ${description}

## Built by the Three-AI Relay

This repo was produced by a chain of AI agents — design → build → integration.

### Files

| File | Source |
|------|--------|
${fileList || '| *(see build_code.txt)* | Claude (build) |'}
| \`design_spec.md\` | Chat Strategic (OpenAI) |
| \`integration_guide.md\` | Gem Bot (Gemini) |

---
*Generated by Three-AI Relay Platform*
`;

  await putFile(token, owner, repoName, 'README.md', readme, 'Add README from Three-AI Relay');

  // Push parsed code files from Claude's build
  if (parsedFiles.length > 0) {
    for (const f of parsedFiles) {
      await putFile(token, owner, repoName, f.path, f.content, `Add ${f.path} (Claude build)`);
    }
  } else if (buildArtifact && buildArtifact.content) {
    // Fallback: push as single file if parser finds nothing
    await putFile(token, owner, repoName, 'build_output.txt', buildArtifact.content, 'Add Claude build output');
  }

  // Push design spec as markdown
  if (designArtifact && designArtifact.content) {
    await putFile(token, owner, repoName, 'design_spec.md', designArtifact.content, 'Add design spec (Chat Strategic)');
  }

  // Push Gemini integration guide as markdown
  if (finalArtifact && finalArtifact.content) {
    await putFile(token, owner, repoName, 'integration_guide.md', finalArtifact.content, 'Add integration guide (Gem Bot)');
  }

  return {
    repo_url: repo.html_url,
    owner,
    repo: repoName,
    files_pushed: parsedFiles.length || 1,
  };
}

module.exports = { deployToGitHub };
